---
- name: Enable Base Configuration
  hosts: all
  roles:
  - base-config

- name: delploy postgresql
  hosts: appdbs
  roles:
  - postgresql

- name: Deploy haproxy
  hosts: frontends
  roles:
  - haproxy
  tags:
    - haproxy

- name: deploy httpd
  hosts: apps
  roles:
  - httpd
  - tomcat

- name: Smoke Test
  hosts: frontends
  tasks:
  - name: test if app is reachable
    uri: 
      url: "http://{{ hostvars[inventory_hostname].ansible_ssh_host }}/"
      return_content: yes
    delegate_to: localhost  
    register:  smoke
    tags:
      - smoke

  - name: check the smoke return page content
    assert:
     that: "'Ansible has done its job - Welcome to Tomcat' in smoke.content" 
    tags:
      - smoke

